name: ActionsTestParent

on: 
  pull_request:
    paths-ignore:
#       - "**/*.md"
      - "website/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Start Check"
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Bearer: ${{ github.token }}" \
          https://api.github.com/repos/rw-extra/Parent/check-runs \
          -d '{"name":"integration_test","head_sha","${{ github.head_ref }}","status":"in_progress"}'
          
#       - name: "Run External Workflow"
#         run: |
#           curl \
#           -X POST \
#           -H "Accept: application/vnd.github+json" \
#           -u ${{ secrets.ACCESS_TOKEN }} \
#           https://api.github.com/repos/OWNER/REPO/dispatches \
#           -d '{"event_type":"start_test","client_payload":{"sha":"${{ github.head_ref }}"}}'
