name: ActionsTestParent

on: 
#   pull_request:
#     paths-ignore:
# #       - "**/*.md"
#       - "website/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
    
      - name: "Let's get it started in here"
        run: |
          echo "Hello from parent in $pwd"
          
      - name: Checkout child
        uses: actions/checkout@v2.5.0
        with:
          repository: "rw-extra/Child"
          ref: main
          path: "build/Child"
          
      - name: Child thing
        uses: rw-extra/Child/.github/workflows/call_me.yml@main
